version: '3'

services:
  # Service MCP standard (mode stdio)
  mcp-server:
    build: ./mcp-server
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - mcp-network
    # Ajout de labels pour Traefik/Coolify
    labels:
      - "traefik.enable=true"
  
  # Service MCP en mode daemon (HTTP)
  mcp-daemon:
    build: ./mcp-server
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - MCP_DAEMON_PORT=3030
    command: node dist/daemon.js
    ports:
      - "3030:3030"
    volumes:
      - mcp-logs:/tmp/mcp-logs
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:3030/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Ajout de labels pour Traefik/Coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mcp-daemon.loadbalancer.server.port=3030"

  mcp-api:
    build: ./mcp-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - mcp-logs:/tmp/mcp-logs
    depends_on:
      - mcp-server
      - mcp-daemon
    environment:
      - NODE_ENV=production
      - PORT=3000
      - USE_MCP_DAEMON=true
      - MCP_DAEMON_HOST=mcp-daemon
      - MCP_DAEMON_PORT=3030
      # Configurer CORS pour autoriser les appels externes (peut être plus restrictif en production)
      - CORS_ALLOW_ORIGIN=*
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O - http://localhost:3000/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Ajout de labels pour Traefik/Coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.mcp-api.loadbalancer.server.port=3000"

volumes:
  mcp-logs:
    driver: local

networks:
  mcp-network:
    driver: bridge
    # Si vous avez besoin de vous connecter à un réseau externe (comme celui de n8n)
    # décommentez les lignes suivantes et remplacez "nom_du_reseau_externe" par le nom du réseau
    # external:
    #   name: nom_du_reseau_externe 